# Site settings
title:       WeWork Engineering
email:       careers@wework.com
author:      WeWork
description: ""
baseurl:     ""
url:         "http://engineering.wework.com"

gems: [jekyll-paginate, jekyll-watch, kramdown, octopress-autoprefixer]

# Permalinks
permalink:        pretty

# Syntax highlighting
highlighter:      rouge

# Segment (for Google Analytics)
segment: gWTkCwUDZBGFC06qFGZAwYDVMgeDWoEj

# Optional features
animated:           false
show_related_posts: true
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: weworkengineering

# Social icons
show_social_icons: false
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share this post:'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
